### ISSUE TITLE
wierd sprites

### ISSUE THREAD

**Issue by cettaur** [coolstation/coolstation#106]
syringe is bad needs rollback or new sprite

screwdriver looks wierd we know you want this one but it look kinda poopy

pda sprite looks like it had a bite taken out of it, maybe rollback or new pda design all together

gasmask sprite is wierd, looks like it was made to go over a helmet

![unknown](https://user-images.githubusercontent.com/109831836/180626663-99149b4e-0189-4d4d-9190-5f7595cb96e4.png)
![unknown (1)](https://user-images.githubusercontent.com/109831836/180626664-b5a70314-bfc9-4847-8535-02025ba78d9e.png)
t

**Comment by geneva-breaker** [comment]
desprited PDAs and with that, this issue is history
