### ISSUE TITLE
handcuffs not showing up in hands slot

### ISSUE THREAD

**Issue by cettaur** [coolstation/coolstation#110]
behold
![image](https://user-images.githubusercontent.com/109831836/180888784-6cb926cf-3c65-45ad-97d2-5084137e2e7a.png)

**Comment by geneva-breaker** [comment]
did this ever work?

**Comment by bobskunk** [comment]
i don't think this ever worked but, it's a good idea
2 handed item handcuffs is a great signifier and you can click them to remove

**Comment by BatElite** [comment]
Done - https://github.com/coolstation/coolstation/commit/c031086e7c5fa2cd019ff2229fdf90b90b0a49fe
