### ISSUE TITLE
empty bullet boxes turn into a bullet

### ISSUE THREAD

**Issue by cettaur** [coolstation/coolstation#112]
behold
![image](https://user-images.githubusercontent.com/109831836/181862697-54c6ee6b-874a-4950-95fb-b0049f67acf6.png)

**Comment by geneva-breaker** [comment]
known bug, but i havent figured out *why*. 
Please add more detail, steps to reproduce, etc

**Comment by geneva-breaker** [comment]
i think this is mostly gone now
