### ISSUE TITLE
The major random event cycle can pick nonexistent events

### ISSUE THREAD

**Issue by BatElite** [coolstation/coolstation#115]
[BUG]

**Describe the bug**
The list for major random events includes a couple of non-functional parent types

**To Reproduce**
For a loose definition of "reproduce" anyway, but here's how to see what I'm talking about without waiting on random rolls for a while:

1 - open the game panel and then the random event controller under coder tools (not the random event controls under admin tools)
2 - scrolls down to the events variable
3 - Observe `datum/random_event_major/antag` and `datum/random_event_major/player_spawn` are in there

**Expected behavior**
No blank events being eligible

**Additional context**
This has probably lead to a significant amount (ratio 2/17) of major random event rolls not doing anything,

**Comment by geneva-breaker** [comment]
why didnt the pr close this? i dont get git
