### ISSUE TITLE
ui tooltips getting stuck

### ISSUE THREAD

**Issue by cettaur** [coolstation/coolstation#168]
the tooltips on the collapsible inventory bar get stuck (apparently only for the classic blue and green ui?)

**Comment by geneva-breaker** [comment]
This is most likely a Cantfix issue with Windows and Byond. Current workaround is to disable tooltips if so desired, or mouseover the lingering tooltip source (usually the UI element that's been updated)

**Comment by geneva-breaker** [comment]
cantfix
