### ISSUE TITLE
Dead people can't hear

### ISSUE THREAD

**Issue by bobskunk** [coolstation/coolstation#171]
[BUG]

**Describe the bug**
So like, it used to be when you died, you'd immediately be able to hear shit. You were dead, so you were treated like a dead chatter.

While alive but in deep crit, you could "barely" hear someone talking or hear something happen. Something happened so that you stay in that hearing state upon death. To hear again you must pop ghost asap (or, well, gib). Deadchat still appears, but it's nice to be able to hear in-round chat too.

**To Reproduce**
1. Die without gibbing
2. Have people talk around you
3. You cannot hear them

**Expected behavior**
When you're dead, you should be able to hear as if you were a ghost.
Maybe even only local speech/audible log lines until you pop ghost?

**Additional context**
Kind of like how when you die, you don't have the blackness of deep crit until you pop ghost, you can suddenly see again.

**Comment by BatElite** [comment]
https://github.com/coolstation/coolstation/commit/1466216e9c7c13f32e33b39bbbe91dce148aab62
