### ISSUE TITLE
it'd be cool if centcomm was on its own Z so ghosts can observe it end of round and during round

### ISSUE THREAD

**Issue by cettaur** [coolstation/coolstation#196]
yeah

**Comment by geneva-breaker** [comment]
This doesnt require its own Z but maybe we can work it out.

**Comment by TheTyrant25** [comment]
if the inside and outside of centcomm are areas i suppose you could code it so that you'd be teleported out on leaving the confines of the building using `Exited()` or `Entered()`

**Comment by geneva-breaker** [comment]
granted
