### ISSUE TITLE
Trader window weirdness

### ISSUE THREAD

**Issue by arborinus** [coolstation/coolstation#199]
[BUG]

**Describe the bug**
At one point in time long ago, a new tgui window was added on top of the older, actual trader window. This new window has never really seen any use besides adding a near-useless button that asks "Who are you?" to the trader. Most people will just select the option to trade with the trader, which closes the new-style window and opens the actual trading window.

This new window is entirely separate. It doesn't have the same checks as the trader window, which was the old "default behavior" when clicking the trader. For example, let's say the trader is annoyed after getting blasted by a laser. The old trading window doesn't open because they are annoyed and won't trade. You can still ask the trader who they are which they will happily respond to, and click the "let's trade!" option only for the trading window to never open.

It's also really obvious the new window is separate when it opens to the spot where the last person who talked to the trader left off. Like if they bought something, then picked it up and walked away, the window will open to the "Thanks for shopping!" message for the next person to open the trader window.

There's also some weirdness about how the window refreshes and closes which messes with people who have issues running tgui windows, but the actual trading window runs just fine.

**Additional context**
honestly I wonder if this newer window can be ripped out without any issue

**Comment by geneva-breaker** [comment]
it can probably be ripped out yes. 
it's for a planned and (at least on our end) unused Trader Dialogue shit that was indev
I think perhaps the only one that ever implemented it was Azungio's NT Bootlicker trader

**Comment by bobskunk** [comment]
yeah, agreeing. good to comment it out and revisit later, it would be nice to have trading window ported but this is just getting in the way

since tgui is tabbed interfaces... that'd make it easier to just have the trading shit up by default and only show dialogue options if they exist. but we'd need a ui wrangler for that

**Comment by BatElite** [comment]
I think the flock trader has a bunch of dialogue (and maybe the owlery bot? can't remember well)

BTW the trader windows are either chui or a regular window styled like chui (I heard that happened too somewhere) so it might be feasible to not touch javascript for this

**Comment by BatElite** [comment]
Bypassed the useless window in https://github.com/coolstation/coolstation/commit/1188d984ecbff349f012ef676d94fab1786a55df
