### ISSUE TITLE
Thindoors go invisible when refusing entry

### ISSUE THREAD

**Issue by BatElite** [coolstation/coolstation#202]
[BUG]

**Describe the bug**
If you can't go through a thindoor it goes invisible for a second.

**To Reproduce**
1. Find a thindoor with access requirements
2. Walk into it

**Expected behavior**
Visible door

**Additional context**
Happens with both the regular ones and the security themed ones that nobody uses anymore.

**Comment by geneva-breaker** [comment]
This was fixed by d57065c4051bd7bba21af0f7be8bc75d345ec499
