### ISSUE TITLE
using floor tiles on space constructions deletes them

### ISSUE THREAD

**Issue by cettaur** [coolstation/coolstation#217]
build a lattice in space using rods then click on them with da floor tiles and it deletes it!!!  also happens for barricades

**Comment by BatElite** [comment]
Isn't that the original purpose of lattices?

**Comment by TheTyrant25** [comment]
barricades are lattices so that tracks
![image](https://github.com/coolstation/coolstation/assets/51260013/b876f394-cb2e-4dfd-b8a8-7d49a83d78e0)

**Comment by TheTyrant25** [comment]
they probably shouldn't be
