### ISSUE TITLE
Can't flip outside on Gehenna

### ISSUE THREAD

**Issue by AXLFAN2000** [coolstation/coolstation#221]
[BUG]

**Describe the bug**
Can't flip outside on Gehenna

**To Reproduce**
1. Gehenna
2. Outside
3. Can't flip

**Expected behavior**
Flip (outside (On Gehenna))

**Screenshots**
![image](https://github.com/coolstation/coolstation/assets/142273065/09da288a-d600-4510-a617-bd8537298bb5)

**Comment by geneva-breaker** [comment]
hyper critical
