### ISSUE TITLE
Stacking ore makes it take up less space in a satchel

### ISSUE THREAD

**Issue by Cartlord** [coolstation/coolstation#223]
[BUG]

**Describe the bug**
I was able to multiply the ore storage of a satchel by 50 by dumping it out, re-stacking the ores, and putting them back in.

**To Reproduce**
1: Mine some ore
2: Put it in a satchel
3: Drop it
4: Stack it with click-drag
5: Put it back in the satchel
6: See the satchel is now MUCH less full

**Expected behavior**
The satchel to still have the same amount of space left

**Screenshots**
None

**Additional context**
I say this multiplies the capacity by 50 because it lets it hold 50 full stacks of ore - or 100, in the case of the large satchel.

**Comment by geneva-breaker** [comment]
This is interesting and wierd behavior, course tbd

**Comment by BatElite** [comment]
Satchels should account for stacked items as of https://github.com/coolstation/coolstation/commit/9ef30ca6281e99ef21dd38ae37832d5099a93643
