### ISSUE TITLE
Inventory UI re-opening

### ISSUE THREAD

**Issue by AXLFAN2000** [coolstation/coolstation#226]
[BUG]

**Describe the bug**
If you view another mobs inventory then close the UI, as long as you're still within a few tiles of them it'll just re-open itself any time their inventory updates (equipping or unequipping something)

**To Reproduce**
1. Open another players inventory
2. Close it
3. They put on a hat
4. Inventory UI reopens for you

**Expected behavior**
Window i closed to Stay Close when i close it

**Screenshots**
ok i would add a silly screenshot but i dont have the game open anymore

**Comment by BatElite** [comment]
Should be fixed by https://github.com/coolstation/coolstation/commit/dc6e82fe449cd335b587945bd73f2ebe6658f9e0
