### ISSUE TITLE
hoodie no sprite

### ISSUE THREAD

**Issue by AXLFAN2000** [coolstation/coolstation#234]
[BUG]

**Describe the bug**
missing hoodie sprite (not there)

**To Reproduce**
1. hoodie
2. wear
3. invisible hoodie
4. 

**Expected behavior**
hoodie

**Screenshots**
artists recreation
![image](https://github.com/coolstation/coolstation/assets/142273065/1a01814e-e808-4efd-9003-bfe1dace97ee)

**Comment by BatElite** [comment]
Have commented out everything but the orange and blue for now, cause that's what we have sprots for
