### ISSUE TITLE
BOBMAP sectech wrong type

### ISSUE THREAD

**Issue by AXLFAN2000** [coolstation/coolstation#236]
[BUG]

**Describe the bug**
suposed to be a sectech but is amory ammotech:-) 

a

**Comment by geneva-breaker** [comment]
were you sec or sec assistant? (none of the ammotechs have access modifiers, but secass dont get access to them in general)

**Comment by AXLFAN2000** [comment]
> were you sec or sec assistant? (none of the ammotechs have access modifiers, but secass dont get access to them in general)

Ah, I was neither, I had just given myself aa  -- if it's tied to the job itself and not sec access that makes sense then.  Want me to close this then, or should that be changed so that sec ID access lets you vend ammo?

**Comment by BatElite** [comment]
The ammotechs have an armory access requirement, but they also use the same sprites as the regular sectechs. Guessing it's just the wrong machine being used.

**Comment by AXLFAN2000** [comment]
That explains it!!! It did have a different stock to the other sec vendors I was used to!  I'll edit the title to reflect that when I'm on my Pc tomorrow then

**Comment by geneva-breaker** [comment]
ok!
