### ISSUE TITLE
Medivape inhand broken

### ISSUE THREAD

**Issue by AXLFAN2000** [coolstation/coolstation#244]
[BUG]

**Describe the bug**
medivape inhand broken

**To Reproduce**
medivape inhand
broken

**Expected behavior**
medivape inhand

**Screenshots**
![image](https://github.com/coolstation/coolstation/assets/142273065/7630af71-f13c-4130-bfcf-fa1e2c0c82b9)

**Additional context**
yea

**Comment by BatElite** [comment]
sorted
