### ISSUE TITLE
portable reclaimer breaks mining satchels

### ISSUE THREAD

**Issue by StardustSkunk** [coolstation/coolstation#263]
[BUG]

**Describe the bug**
Any time a full mining ore satchel is used on the portable reclaimer the satchel is unloaded into it as expected, but the satchel sprite is frozen to when it was still full and the item does not seem to do any normal functions after that.
The ore scoop just dumps whatever is in the satchel onto the tile the reclaimer is on.

Further Testing revealed the state of how many ores are inside is separate to how many ores are shown by the UI elements (description/sprite) to be in the satchel, regardless of size.
Putting more ore will increase the number starting from what is shown by the UI, yet still only have as many ores are actually placed into it.
Emptying an "out of sync" mining satchel with at least one "real" ore in it will reset the displayed amount to zero, making it act normally again.

**To Reproduce**
For example emptying a satchel with 13 rocks inside into the portable reclaimer will put 13 rocks in, and allow you to make 13 rock bars.
Yet, doing so will still show up in the UI as before with 13 rocks in the satchel.
Placing 2 more rocks in will raise the number displayed to 15, yet when used on the reclaimer only the two placed in the satchel will be used.
Placing one more rock will increase the number to 16, and dumping the satchel onto the floor will reset the number back to zero and leave one rock on the floor.

**Additional context**
Originally posted to the forums here
https://forum.coolstation.space/viewtopic.php?t=161

**Comment by BatElite** [comment]
didn't I fix this a while back?

**Comment by StardustSkunk** [comment]
Seems you have, my mistake.
