### ISSUE TITLE
Chat window (possibly other things) fails to load until mismatched cert is accepted

### ISSUE THREAD

**Issue by bobskunk** [coolstation/coolstation#268]
[BUG]

**Describe the bug**
When connecting to fusilli, there's a cert prompt:
![image](https://github.com/coolstation/coolstation/assets/89719735/55cdf812-9c9a-4178-a709-16dba3ddd9f9)

The cert is issued to blog.stackpath.com, and was valid from 3/28/2024, so it's possible this was a recent change to whatever this chat window stuff touches.

**To Reproduce**
1. Connect to fusilli.coolstation.space
2. Wait for interface to load, cert popup will show up.
3a. Click Yes on cert popup, chat appears, but more prompts appear.
3b. Click No on cert popup, chat still unavailable, another prompt appears continually.

**Expected behavior**
Chat should work with no prompts or cert messing-with (and it's horrendously bad practice to tell anyone anywhere to just click yes on a cert mismatch popup)

**Comment by SpacingNevada** [comment]
browserOutput.html was asking for a script from a CDN that doesn't exist anymore. Switched the URL as recommended by Twemoji
https://github.com/twitter/twemoji
