### ISSUE TITLE
move-while-buckled chair speed is goofed up

### ISSUE THREAD

**Issue by bobskunk** [coolstation/coolstation#278]
[BUG]

**Describe the bug**
moving around in a chair is too fast, recent unintended behavior

**To Reproduce**
1. buckle into a chair
2. move around
3. gotta go fast

**Expected behavior**
Movement closer to one tile a second on wheels, one tile two seconds on regular legs.

**Additional context**
two possible culprits: life loop halving and my semi-done stools

**Comment by geneva-breaker** [comment]
This does not seem to be a problem anymore
