### ISSUE TITLE
Latejoining as an engineer on chunk leaves you ass naked

### ISSUE THREAD

**Issue by klushy225** [coolstation/coolstation#283]
[BUG]

**Describe the bug**
If you late join as an engineer on chunk you spawn in completely naked with a  basic backpack and a civilian headset

EDIT: You do get your ID in your backpack at least
**To Reproduce**
1. wait for the round to start on chunk
2. latejoin as an engineer

**Expected behavior**
1. to spawn with basic engineer gear and clothes
**Screenshots**
![image](https://github.com/user-attachments/assets/0827545f-06be-44b4-a505-a2d3ed838fe6)

**Additional context**
I spawned in as a mutantrace, but that's about the only important factor I can think of

**Comment by klushy225** [comment]
*you actually do get an engineering headset

**Comment by geneva-breaker** [comment]
oh yeah bob fixed this
