### ISSUE TITLE
you can writhe around while you're dead and not ghosted

### ISSUE THREAD

**Issue by klushy225** [coolstation/coolstation#284]
[BUG]

**Describe the bug**
If you die, and have not ghosted, you can spam movement keys to writhe your corpse around.
**To Reproduce**
1. Die
2. Do not ghost
3. mash those wasd keys
**Expected behavior**
For the body to remain still(controls locked if you're dead)

**Screenshots**

**Additional context**

**Comment by geneva-breaker** [comment]
yeah its been like this for years, probably won't fix just because it's harmless and it's kind of become a tell/sign that you're still around like chairspinning.

**Comment by geneva-breaker** [comment]
https://discord.com/channels/880554731452383312/949374669646082128/1297054256452599818
