### ISSUE TITLE
weird layering/missing hand?

### ISSUE THREAD

**Issue by AXLFAN2000** [coolstation/coolstation#287]
[BUG]

**Describe the bug**
wearing default janitor gear (janitor jumpsuit grey backpack no gloves) hand is invisible when looking left but visible when looking right
 
**To Reproduce**
1. be janitor
2. look right (see beautiful hand)
3. look left (hand missing..??)
4.  also be bug ??? honestly i have no idae what is the problematic element here. but heres a pictures.

**Expected behavior**
hand

**Screenshots**
![image](https://github.com/user-attachments/assets/a224def8-4311-4362-809f-e64593869636)
also when looking right the hand is widely long so im thinking maybe my left hand is on the right side but i dont know what that means. i dont know what any of this means.
![image](https://github.com/user-attachments/assets/f5c5f1b7-7dc1-49f5-80a1-a83c1b90ddb3)

**Comment by AXLFAN2000** [comment]
thinking this is a roach thing maybe because its happening on other outfits too

**Comment by geneva-breaker** [comment]
ohhum whtf

**Comment by BatElite** [comment]
error in the hand sprites, fixed now
