### ISSUE TITLE
Audiolog recordings omitting first spoken line

### ISSUE THREAD

**Issue by bobskunk** [coolstation/coolstation#293]
[BUG]

**Describe the bug**
Relayed by Couturier:
First recorded line of audio logs is omitted on playback or recording.

**To Reproduce**
1. Pick up tape recorder with tape ready to record.
2. Start recording
3. Speak several lines, stop recording.
4. Play back and compare output to input: first spoken line is missing.

**Expected behavior**
Everything said in range while recording should be played back, including the first line.

**Additional context**
"Gave it five tries to confirm, wiped the tape and started over, etc."

**Comment by geneva-breaker** [comment]
![image](https://github.com/user-attachments/assets/f572daa0-105f-4cfc-9e3a-1eb6abae4a41)

**Comment by geneva-breaker** [comment]
![image](https://github.com/user-attachments/assets/cdfec857-1768-491b-9e61-dc9b8daada19)

**Comment by geneva-breaker** [comment]
real interesting 
![image](https://github.com/user-attachments/assets/f32310c8-b6c0-46dc-b781-6cc37e86a71b)

**Comment by geneva-breaker** [comment]
plays correctly when stopping and starting, missis first entry only when looping

**Comment by geneva-breaker** [comment]
lmfao rookie shit 
![image](https://github.com/user-attachments/assets/6dc513f3-b10e-4165-9964-4e0475627abc)
