### ISSUE TITLE
fluid depth overlays not behaving as expected

### ISSUE THREAD

**Issue by geneva-breaker** [coolstation/coolstation#294]
[BUG]

**Describe the bug**
Not sure how much this is "a bug" and how much is just that we fucked around with the perspective overlays so it doesnt work anymore, but there's like no feedback that the fluid in a room is getting up to your neck before you start drowning. the color covers *some* objects and mobs at a fairly low depth (ex: mickey mouse) but the player mob is never overlaid even when drowning. I think i remember this working not very long ago. 

**To Reproduce**
stand in a room and flood it.

**Expected behavior**
overlays covering 1/4, 1/2, and 3/4 of the mob as the fluid rises.

**Comment by BatElite** [comment]
Finding that the fluid overlays only update if you move in or out of a fluid (as in, mob movement)

Haven't yet found the appriopriate place in code to fix.

**Comment by BatElite** [comment]
:|
![image](https://github.com/user-attachments/assets/805858c4-1033-450c-a14c-2739db4f589e)

**Comment by BatElite** [comment]
enabled some shit, if it's too performance intensive we can look at it later
