### ISSUE TITLE
Weird spief bounty interaction

### ISSUE THREAD

**Issue by AXLFAN2000** [coolstation/coolstation#306]
[BUG]

**Describe the bug**
my ID was a bounty reward, I tried to put my ID into my PDA (instead of hitting my ID with my PDA) like normal and it ate it for the bounty instead and the bounty is listed as claimed but I didn't get the item 

**To Reproduce**
1. my ID was a bounty
2. Put ID into PDA
3. gone
4. no bounty item either

**Expected behavior**
IMO, you should be able to put your ID into your pda like normal, and if you want to claim it, hit the ID with the PDA like you do with claiming other rewards.  but regardless of that, submitting a bounty should drop the item lol

**Comment by BatElite** [comment]
tried to do the slap-PDA-on-ID method after patching and god the reward, so I'm presuming this is fixed
